/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fuga.de.letras;

/**
 *
 * @author Alejandro
 */
public class VentanaJuego2 extends javax.swing.JFrame {

    /**
     * Creates new form VentanaJuego2
     */
    public VentanaJuego2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPalabra = new javax.swing.JLabel();
        btnA = new javax.swing.JButton();
        btnE = new javax.swing.JButton();
        btnI = new javax.swing.JButton();
        btnO = new javax.swing.JButton();
        btnU = new javax.swing.JButton();
        lblContadorPalabras = new javax.swing.JLabel();
        lbnContadorErrores = new javax.swing.JLabel();
        lbnContadorCorresctas = new javax.swing.JLabel();
        btnTerminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FUGA DE LETRAS.");
        setPreferredSize(new java.awt.Dimension(855, 480));
        setResizable(false);

        lblPalabra.setFont(new java.awt.Font("Arial Narrow", 1, 60)); // NOI18N
        lblPalabra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPalabra.setText("hola");
        lblPalabra.setToolTipText("");

        btnA.setBackground(new java.awt.Color(248, 206, 204));
        btnA.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        btnA.setMnemonic('a');
        btnA.setText("A");
        btnA.setPreferredSize(new java.awt.Dimension(100, 100));
        btnA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAActionPerformed(evt);
            }
        });

        btnE.setBackground(new java.awt.Color(225, 213, 231));
        btnE.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        btnE.setText("E");
        btnE.setPreferredSize(new java.awt.Dimension(100, 100));
        btnE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEActionPerformed(evt);
            }
        });

        btnI.setBackground(new java.awt.Color(248, 206, 204));
        btnI.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        btnI.setText("I");
        btnI.setPreferredSize(new java.awt.Dimension(100, 100));

        btnO.setBackground(new java.awt.Color(225, 213, 231));
        btnO.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        btnO.setText("O");
        btnO.setMinimumSize(new java.awt.Dimension(100, 100));
        btnO.setPreferredSize(new java.awt.Dimension(100, 100));

        btnU.setBackground(new java.awt.Color(248, 206, 204));
        btnU.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        btnU.setText("U");
        btnU.setPreferredSize(new java.awt.Dimension(100, 100));
        btnU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUActionPerformed(evt);
            }
        });

        lblContadorPalabras.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        lblContadorPalabras.setText("PALABRAS: ");

        lbnContadorErrores.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        lbnContadorErrores.setText("ERRORES:");

        lbnContadorCorresctas.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        lbnContadorCorresctas.setText("CORRECTAS: ");

        btnTerminar.setBackground(new java.awt.Color(255, 30, 29));
        btnTerminar.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        btnTerminar.setText("TERMINAR INTENTO");
        btnTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(lblContadorPalabras)
                        .addGap(205, 205, 205)
                        .addComponent(lbnContadorErrores)
                        .addGap(208, 208, 208)
                        .addComponent(lbnContadorCorresctas))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(lblPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(btnA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(btnE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(btnI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(btnO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(btnU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(btnTerminar)))
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblContadorPalabras)
                    .addComponent(lbnContadorErrores)
                    .addComponent(lbnContadorCorresctas))
                .addGap(69, 69, 69)
                .addComponent(lblPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(btnTerminar)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAActionPerformed

    private void btnEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEActionPerformed

    private void btnUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUActionPerformed

    private void btnTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminarActionPerformed
        VentanaEstadisticas newframeEstadisticas = new VentanaEstadisticas();       //crea frame pra llevar a la ventana estadisticas
        
        newframeEstadisticas.setVisible(true);      //usando el frame inicia VentanaEstadisticas
        
        this.dispose();     //evita la acomulacion de ventanas
    }//GEN-LAST:event_btnTerminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaJuego2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnA;
    private javax.swing.JButton btnE;
    private javax.swing.JButton btnI;
    private javax.swing.JButton btnO;
    private javax.swing.JButton btnTerminar;
    private javax.swing.JButton btnU;
    private javax.swing.JLabel lblContadorPalabras;
    private javax.swing.JLabel lblPalabra;
    private javax.swing.JLabel lbnContadorCorresctas;
    private javax.swing.JLabel lbnContadorErrores;
    // End of variables declaration//GEN-END:variables
}
