/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import eventos.Jugador;
import eventos.Palabras;
import java.util.Random;

/**
 *
 * @author Alejandro
 */
public class VentanaJuego1 extends javax.swing.JFrame {

    /**
     * Creates new form VentanaJuego1
     */
    public VentanaJuego1() {
        initComponents();
    }
    
    Jugador datosjJugador = new Jugador();
    Palabras palabra = new Palabras();
    VentanaJuego2 v2 = new VentanaJuego2();
    VentanaEstadisticas ventanaes = new VentanaEstadisticas();
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtNombre = new javax.swing.JTextArea();
        lblNombre = new javax.swing.JLabel();
        lblTematica = new javax.swing.JLabel();
        btnAnimales = new javax.swing.JButton();
        btnColores = new javax.swing.JButton();
        btnFrutas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FUGA DE LETRAS.");
        setResizable(false);

        txtNombre.setFont(new java.awt.Font("Arial Narrow", 0, 32)); // NOI18N
        jScrollPane1.setViewportView(txtNombre);

        lblNombre.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        lblNombre.setText("NOMBRE.");

        lblTematica.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        lblTematica.setForeground(java.awt.Color.red);
        lblTematica.setText("ELIGE UNA TEMATICA.");

        btnAnimales.setBackground(new java.awt.Color(255, 213, 231));
        btnAnimales.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        btnAnimales.setText("ANIMALES");
        btnAnimales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAnimalesMousePressed(evt);
            }
        });

        btnColores.setBackground(new java.awt.Color(248, 206, 204));
        btnColores.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        btnColores.setText("COLORES");
        btnColores.setPreferredSize(new java.awt.Dimension(150, 50));
        btnColores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnColoresMousePressed(evt);
            }
        });

        btnFrutas.setBackground(new java.awt.Color(255, 230, 204));
        btnFrutas.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        btnFrutas.setText("FRUTAS");
        btnFrutas.setMinimumSize(new java.awt.Dimension(93, 28));
        btnFrutas.setPreferredSize(new java.awt.Dimension(150, 50));
        btnFrutas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnFrutasMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(220, 220, 220))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(390, 390, 390)
                        .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(btnAnimales, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnColores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTematica))
                        .addGap(63, 63, 63)
                        .addComponent(btnFrutas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNombre)
                .addGap(94, 94, 94)
                .addComponent(lblTematica)
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnimales, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnColores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFrutas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnimalesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnimalesMousePressed
        VentanaJuego2 newframeJuego2 = new VentanaJuego2();     //crea frame para iniciar VentanaJuego2
        
        newframeJuego2.setVisible(true);    //usando el frame inicia VentanaJuego2
        
        this.dispose();     //evita acomulacion de ventanas
        
        datosjJugador.obtenerNombre();      //obtiene nombre del jugador
        datosjJugador.imprimirDato();       //muestra mensaje de confimacion de nombre
        
        VentanaJuego2.actualizarPalabra(palabra.seleccionAnimal());
        
    }//GEN-LAST:event_btnAnimalesMousePressed

    private void btnColoresMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnColoresMousePressed
        VentanaJuego2 newframeJuego2 = new VentanaJuego2();     //crea frame para iniciar VentanaJuego2
        
        newframeJuego2.setVisible(true);    //usando el frame inicia VentanaJuego2
        
        this.dispose();     //evita acomulacion de ventanas
        
        datosjJugador.obtenerNombre();      //obtiene nombre del jugador
        datosjJugador.imprimirDato();       //muestra mensaje de confimacion de nombre
        
        VentanaJuego2.actualizarPalabra(palabra.seleccionColor());
    }//GEN-LAST:event_btnColoresMousePressed

    private void btnFrutasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFrutasMousePressed
        VentanaJuego2 newframeJuego2 = new VentanaJuego2();     //crea frame para iniciar VentanaJuego2
        
        newframeJuego2.setVisible(true);    //usando el frame inicia VentanaJuego2
        
        this.dispose();     //evita acomulacion de ventanas
        
        datosjJugador.obtenerNombre();      //obtiene nombre del jugador
        datosjJugador.imprimirDato();       //muestra mensaje de confimacion de nombre
        
        VentanaJuego2.actualizarPalabra(palabra.seleccionFruta());
    }//GEN-LAST:event_btnFrutasMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaJuego1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnimales;
    private javax.swing.JButton btnColores;
    private javax.swing.JButton btnFrutas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTematica;
    public static javax.swing.JTextArea txtNombre;
    // End of variables declaration//GEN-END:variables
}
